### ISSUE TITLE
lastItemの初期化について

### ISSUE THREAD

**Issue by CherryPetale** [ingen084/KyoshinEewViewerIngen#1]
初めまして。
一点確認したいのですが、以下のコードにあるlastItemは初期化しなくてよいでしょうか。
一個上のP波を計算するところでlastItemに値が入った状態になるのでif文の条件が無効になっている気がします。

https://github.com/ingen084/KyoshinEewViewerIngen/blob/a6f2812399b7dc252e681ec9ba6dd5a41304fe65/src/KyoshinEewViewer/Services/TrTimeTableService.cs#L45

**Comment by ingen084** [comment]
はじめまして。
この処理は読み込む走時表が時系列順に並んでいることを前提としたコードです。
S波の `lastItem == null` の条件式でP波のループの値が入っている状態にするためには、
1つ目の TimeTable において `item.PTime > elapsedTime` が1度以上マッチしないかつ、 `item.STime > elapsedTime` が1度目でマッチするといった状況が発生する必要があります。
ですが、基本的にP波はS波よりも早いという原則があり、不正なデータでない限り上記の条件に当てはまることはありません。
そのため特に問題なく動作しています。

いずれにせよ理解しづらいコードなので書き直したいですね…。

**Comment by CherryPetale** [comment]
そうだったんですね。前提知識が乏しすぎて勘違いしてました。
こういう複雑な処理ってなかなか最適化難しいですよね。
お手数おかけしました…。クローズしますね。
