### ISSUE TITLE
台風情報を表示出来るようにする

### ISSUE THREAD

**Issue by Kawaharu869** [ingen084/KyoshinEewViewerIngen#101]
台風情報を実装
（機能強化）
![スクリーンショット 2024-01-24 003720](https://github.com/ingen084/KyoshinEewViewerIngen/assets/116153360/58240d4d-6fc3-4499-8abd-92a988cad811)

**Comment by ingen084** [comment]
https://github.com/ingen084/KyoshinEewViewerIngen/issues/34 すでにここにあります！
