### ISSUE TITLE
海底地震計の表示

### ISSUE THREAD

**Issue by Kawaharu869** [ingen084/KyoshinEewViewerIngen#102]
まぁあったら便利（？）
![image](https://github.com/ingen084/KyoshinEewViewerIngen/assets/116153360/320a3d63-8217-42af-b8fa-ed2389ff2611)

**Comment by ingen084** [comment]
海しるを使った物を想定されているでしょうか。であれば3分ごとの更新となってしまうためリアルタイムでもない、という問題もあり組み込むのは難しそうです。

**Comment by Kawaharu869** [comment]
リアルタイムで受信できる手段があればいいんですけどね...
じゃあCloseしま～す
