### ISSUE TITLE
震度5-以上未入電に対応

### ISSUE THREAD

**Issue by Kawaharu869** [ingen084/KyoshinEewViewerIngen#105]
地震情報の JmaIntensity を KyoshinMonitorLib から切り離し、 震度5弱以上未入電 に対応します

ロードマップから

**Comment by K-Haruki-0206** [comment]
見た目は...
未入電観測点を？で表示するとか

**Comment by ingen084** [comment]
現状表示は出来ていて機能は問題ないこと、起票者の意思があまりなさそうな点から一旦 close します
