### ISSUE TITLE
完全自動アップデートを実装

### ISSUE THREAD

**Issue by Kawaharu869** [ingen084/KyoshinEewViewerIngen#106]
イベント中にアップデートされないようにとか、バグ混入のバージョンがアップデートされないよう気をつける必要あり
緊急地震速報発表中や地震検知時、バグ入りのバージョンがアップデートされないようにする必要があります

ロードマップから

**Comment by ingen084** [comment]
ロードマップに書いてあってissueになっていないものはまだ実装が確定していなかったり内容が決め切れていない物なので、issueにする際はアイデアをいただけるとありがたく…。

**Comment by ingen084** [comment]
起票者の意思があまりなさそうな点から一旦 close します
