### ISSUE TITLE
設定ウィンドウが特定のサイズのとき、緊急地震速報タブ内の文章に脱字が発生する

### ISSUE THREAD

**Issue by ziopuzzle** [ingen084/KyoshinEewViewerIngen#11]
### 不具合内容
「設定>緊急地震速報タブ>このソフトの緊急地震速報の受信について」の文章が設定ウィンドウの横幅によって、最後の一文が「注意てください。」のように脱字されて表示されます。設定ウィンドウが短すぎまたは長すぎても発生しません。
具体的には、設定ウィンドウを開いたときの横幅±10pxぐらいのときに発生します。

### 環境
OS：Windows10
ソフトウェアバージョン：v0.9.23.0-ALPHA（merged版を使用）

### スクリーンショット
脱字発生
![脱字発生（設定ウィンドウを開いたときのサイズ）](https://user-images.githubusercontent.com/24411192/118230292-640d8a80-b4c8-11eb-90a5-bb53efc6e294.png)

脱字未発生
![不具合未発生（サイズをデフォルトより横に広げる）](https://user-images.githubusercontent.com/24411192/118230402-961eec80-b4c8-11eb-9eaf-22b71e47c1f2.png)

### 備考
Light、Darkテーマで検証しましたが同様の不具合が発生したためテーマ依存ではなさそうです。

**Comment by ingen084** [comment]
ありがとうございます。
フレームワーク側のバグっぽいですね…一旦次のビルドで文字折返しのオプションを変更してみます。
現状このソフトの変更のみでは根本的な解決はできなさそうなので、Issue自体は開きっぱなしにしておきます。

**Comment by ziopuzzle** [comment]
いつからかは不明ですが、再発してるっぽい？
現バージョン（v0.10.31.93 merged）で確認

**Comment by ingen084** [comment]
文言をちょっと変更しただけでずっと発生していて、どうやらフレームワーク側での文字幅の認識とそこからの折返しの処理に問題があるようです。
原因が特定できたらフレームワーク本体の方にPRが出せればなと思っています

**Comment by ingen084** [comment]
原因を特定できたのでフレームワークにPRを出しています
https://github.com/AvaloniaUI/Avalonia/pull/7397

**Comment by ingen084** [comment]
0.10.48で対策完了しましたのでcloseします！
