### ISSUE TITLE
等倍スケーリングで表示文字が荒い

### ISSUE THREAD

**Issue by boocsan** [ingen084/KyoshinEewViewerIngen#13]
![image](https://user-images.githubusercontent.com/32415097/121806557-4b40f200-cc8b-11eb-81fa-b8e862b2dfd0.png)

高 DPI 環境ではきれいに表示されるが 1080p な27インチモニターなどでは荒く表示される模様

**Comment by ingen084** [comment]
フォントが悪いんですよねこれ…なにかいいフォントがあればぜひ(システムフォントでもいいと言う説はあります)

**Comment by ingen084** [comment]
@iedred7584 現在のバージョンの描画はいかがでしょうか・・・まだ荒いですかね？

**Comment by boocsan** [comment]
すみません、失念していました
等倍でもきれいに表示されているので解決されています！

**Comment by ingen084** [comment]
ありがとうございます！
