### ISSUE TITLE
Windowsでexplorerが再起動した際にタスクアイコンの再設定がされない

### ISSUE THREAD

**Issue by ziopuzzle** [ingen084/KyoshinEewViewerIngen#134]
explorerが何らかの事由で再起動するとタスクバーがリセットされ、通知領域のアイコンが登録解除されているかと思われます。
![image](https://github.com/user-attachments/assets/d209dd95-303c-42dc-b7a6-38c049b53ede)

参考情報
https://learn.microsoft.com/ja-jp/windows/win32/shell/taskbar?redirectedfrom=MSDN#taskbar-creation-notification
> Microsoft Internet エクスプローラー 4.0 以降では、シェルはタスク バーが作成されたことをアプリケーションに通知します。 タスク バーが作成されると、タスク バーの作成文字列にメッセージが登録され、このメッセージがすべての最上位ウィンドウにブロードキャストされます。 タスク バー アプリケーションがこのメッセージを受信すると、追加したタスク バー アイコンが削除されたと想定し、再度追加する必要があります。

**Comment by ingen084** [comment]
0.19.3 で対応完了しました！
